### signup
@url_dev = http://localhost:3000/v1/api

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Test Shop",
    "email": "shop@gmail.com",
    "password": "password123"
}
